import type { SectionConfig } from './types'

export const sectionConfig: Record<string, SectionConfig> = {
  navbar: {
    label: 'Barra de navegación',
    icon: '🧭',
    fields: [
      { key: 'logo_text', label: 'Texto del logo', type: 'text' },
      { key: 'logo_span', label: 'Texto dorado del logo', type: 'text' },
      { key: 'donate_text', label: 'Texto botón donar', type: 'text' },
    ],
  },
  hero: {
    label: 'Hero (Inicio)',
    icon: '🏠',
    fields: [
      { key: 'badge', label: 'Badge', type: 'text' },
      { key: 'title', label: 'Título principal', type: 'text' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'stats_years', label: 'Años (valor)', type: 'text' },
      { key: 'stats_years_label', label: 'Años (etiqueta)', type: 'text' },
      { key: 'stats_lives', label: 'Vidas (valor)', type: 'text' },
      { key: 'stats_lives_label', label: 'Vidas (etiqueta)', type: 'text' },
      { key: 'stats_centers', label: 'Sucursales (valor)', type: 'text' },
      { key: 'stats_centers_label', label: 'Sucursales (etiqueta)', type: 'text' },
    ],
  },
  quienes_somos: {
    label: 'Quiénes Somos',
    icon: '🌿',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'intro', label: 'Texto introductorio', type: 'textarea' },
      { key: 'mision_title', label: 'Título Misión', type: 'text' },
      { key: 'mision', label: 'Misión', type: 'textarea' },
      { key: 'vision_title', label: 'Título Visión', type: 'text' },
      { key: 'vision', label: 'Visión', type: 'textarea' },
      { key: 'objetivos_title', label: 'Título Objetivos', type: 'text' },
      { key: 'objetivos', label: 'Objetivos', type: 'textarea' },
      { key: 'director_title', label: 'Cargo del director', type: 'text' },
      { key: 'director_desc', label: 'Descripción del director', type: 'textarea' },
      { key: 'floating_number', label: 'Número flotante', type: 'text' },
      { key: 'floating_label', label: 'Etiqueta flotante', type: 'text' },
    ],
  },
  servicios: {
    label: 'Servicios',
    icon: '🤝',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'desc', label: 'Descripción', type: 'textarea' },
      { key: 'rehab_title', label: 'Título (rehabilitación)', type: 'text' },
      { key: 'rehab_text', label: 'Texto (rehabilitación)', type: 'textarea' },
      { key: 'hombre_title', label: 'Título (hombres)', type: 'text' },
      { key: 'hombre_text', label: 'Texto (hombres)', type: 'textarea' },
      { key: 'mujer_title', label: 'Título (mujeres)', type: 'text' },
      { key: 'mujer_text', label: 'Texto (mujeres)', type: 'textarea' },
      { key: 'proyecto_title', label: 'Título del proyecto', type: 'text' },
      { key: 'objetivos_title', label: 'Título objetivos del tratamiento', type: 'text' },
      { key: 'objetivos_text', label: 'Objetivos del tratamiento', type: 'textarea' },
      { key: 'espera_title', label: 'Título "Lo que se espera"', type: 'text' },
      { key: 'espera_text', label: 'Lo que se espera', type: 'textarea' },
    ],
  },
  instalaciones: {
    label: 'Instalaciones y Equipos',
    icon: '🏛️',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'desc', label: 'Descripción', type: 'textarea' },
      { key: 'profesionales_title', label: 'Título Profesionales', type: 'text' },
      { key: 'profesionales_text', label: 'Texto Profesionales', type: 'textarea' },
      { key: 'persona_title', label: 'Título concepción de la persona', type: 'text' },
      { key: 'persona_text', label: 'Concepción de la persona', type: 'textarea' },
      { key: 'ubicacion_text', label: 'Texto ubicación', type: 'textarea' },
      { key: 'principios_title', label: 'Título Principios de operación', type: 'text' },
      { key: 'principios_text_1', label: 'Principios (párrafo 1)', type: 'textarea' },
      { key: 'principios_text_2', label: 'Principios (párrafo 2)', type: 'textarea' },
      { key: 'principios_text_3', label: 'Principios (párrafo 3)', type: 'textarea' },
    ],
  },
  radio: {
    label: 'Radio El Edén',
    icon: '📻',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'text', label: 'Texto descriptivo', type: 'textarea' },
      { key: 'status_text', label: 'Estado (ej: En vivo)', type: 'text' },
      { key: 'btn_text', label: 'Texto del botón', type: 'text' },
      { key: 'btn_url', label: 'URL del botón', type: 'text' },
    ],
  },
  videos: {
    label: 'Videos',
    icon: '🎬',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'text', label: 'Texto', type: 'textarea' },
      { key: 'video_1_url', label: 'URL video 1 (YouTube/embed)', type: 'text' },
      { key: 'video_2_url', label: 'URL video 2', type: 'text' },
      { key: 'video_3_url', label: 'URL video 3', type: 'text' },
    ],
  },
  testimonios: {
    label: 'Testimonios',
    icon: '💬',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'quote', label: 'Cita textual', type: 'textarea' },
      { key: 'author_name', label: 'Nombre del autor', type: 'text' },
      { key: 'author_role', label: 'Rol del autor', type: 'text' },
    ],
  },
  donaciones: {
    label: 'Donaciones',
    icon: '❤️',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'text', label: 'Texto', type: 'textarea' },
      { key: 'amount_1', label: 'Monto 1', type: 'text' },
      { key: 'label_1', label: 'Etiqueta 1', type: 'text' },
      { key: 'url_1', label: 'URL 1', type: 'text' },
      { key: 'amount_2', label: 'Monto 2', type: 'text' },
      { key: 'label_2', label: 'Etiqueta 2', type: 'text' },
      { key: 'url_2', label: 'URL 2', type: 'text' },
      { key: 'amount_3', label: 'Monto 3', type: 'text' },
      { key: 'label_3', label: 'Etiqueta 3', type: 'text' },
      { key: 'url_3', label: 'URL 3', type: 'text' },
      { key: 'amount_4', label: 'Monto 4', type: 'text' },
      { key: 'label_4', label: 'Etiqueta 4', type: 'text' },
      { key: 'url_4', label: 'URL 4', type: 'text' },
      { key: 'amount_5', label: 'Monto 5', type: 'text' },
      { key: 'label_5', label: 'Etiqueta 5', type: 'text' },
      { key: 'url_5', label: 'URL 5', type: 'text' },
      { key: 'amount_6', label: 'Monto 6', type: 'text' },
      { key: 'label_6', label: 'Etiqueta 6', type: 'text' },
      { key: 'url_6', label: 'URL 6', type: 'text' },
      { key: 'single_title', label: 'Título donación única', type: 'text' },
      { key: 'single_text', label: 'Texto donación única', type: 'textarea' },
      { key: 'single_btn_text', label: 'Texto botón donación única', type: 'text' },
      { key: 'single_url', label: 'URL donación única', type: 'text' },
    ],
  },
  admision: {
    label: 'Requisitos de Admisión',
    icon: '📋',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'text', label: 'Texto introductorio', type: 'textarea' },
      { key: 'req_1', label: 'Requisito 1', type: 'text' },
      { key: 'req_2', label: 'Requisito 2', type: 'text' },
      { key: 'req_3', label: 'Requisito 3', type: 'text' },
      { key: 'req_4', label: 'Requisito 4', type: 'text' },
      { key: 'req_5', label: 'Requisito 5', type: 'text' },
      { key: 'req_6', label: 'Requisito 6', type: 'text' },
      { key: 'req_7', label: 'Requisito 7', type: 'text' },
      { key: 'req_8', label: 'Requisito 8', type: 'text' },
    ],
  },
  contacto: {
    label: 'Contacto',
    icon: '✉️',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'text', label: 'Texto', type: 'textarea' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'whatsapp_masculino', label: 'WhatsApp Masculino', type: 'text' },
      { key: 'whatsapp_femenino', label: 'WhatsApp Femenino', type: 'text' },
      { key: 'address_label_1', label: 'Etiqueta dirección 1', type: 'text' },
      { key: 'address_1', label: 'Dirección 1', type: 'text' },
      { key: 'address_label_2', label: 'Etiqueta dirección 2', type: 'text' },
      { key: 'address_2', label: 'Dirección 2', type: 'text' },
      { key: 'address_label_3', label: 'Etiqueta dirección 3', type: 'text' },
      { key: 'address_3', label: 'Dirección 3', type: 'text' },
      { key: 'address_label_4', label: 'Etiqueta dirección 4', type: 'text' },
      { key: 'address_4', label: 'Dirección 4', type: 'text' },
      { key: 'note', label: 'Nota adicional', type: 'textarea' },
      { key: 'instagram_url', label: 'URL Instagram', type: 'text' },
    ],
  },
  yo_soy_socio: {
    label: 'Yo Soy Socio',
    icon: '🤲',
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'text_1', label: 'Texto 1', type: 'textarea' },
      { key: 'text_2', label: 'Texto 2', type: 'textarea' },
      { key: 'socio_name', label: 'Nombre del socio', type: 'text' },
      { key: 'socio_desc', label: 'Descripción del socio', type: 'textarea' },
    ],
  },
  footer: {
    label: 'Footer',
    icon: '🔻',
    fields: [
      { key: 'brand_text', label: 'Texto de marca', type: 'textarea' },
      { key: 'copyright', label: 'Copyright', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Teléfono / WhatsApp', type: 'text' },
      { key: 'address', label: 'Dirección', type: 'text' },
      { key: 'facebook', label: 'Facebook URL', type: 'text' },
      { key: 'instagram', label: 'Instagram URL', type: 'text' },
      { key: 'youtube', label: 'YouTube URL', type: 'text' },
    ],
  },
}

export const sectionKeys = Object.keys(sectionConfig)
