services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - UPLOADS_DIR=/app/dist/client/uploads
    volumes:
      - db_data:/app/db
      - uploads_data:/app/dist/client/uploads
    restart: unless-stopped

volumes:
  db_data:
  uploads_data:
